name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
#   test:
#     name: Run Unit Tests
#     runs-on: ubuntu-18.04

#     steps:
#       - uses: actions/checkout@v1
#       - name: set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8
#       - name: Unit tests
#         run: bash ./gradlew test --stacktrace

  apkbuild:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build release APK
        run: bash ./gradlew assembleRelease -PbuildDir="app/release/"
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/release/app-release.apk
          
  push:
      name: Publish to Playstore
      needs: apkbuild
      runs-on: ubuntu-18.04
      env:
        whatsnew: distribution/whatsnew
        mapping: app/release/mapping/mapping.txt

      steps:
        - name: Download APK from artifact
          uses: actions/download-artifact@v1
          with:
            name: apk
        - name: Push to playstore
          uses: r0adkll/upload-google-play@v1
          with:
            serviceAccountJsonPlainText: ${{ secrets.serviceAccount }}
            packageName: com.darvis.redisandroid
            releaseFile: apk
            track: internal
            userFraction: 0.33
            whatsNewDirectory: $whatsnew
            mappingFile: $mapping
