name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
#   test:
#     name: Run Unit Tests
#     runs-on: ubuntu-18.04

#     steps:
#       - uses: actions/checkout@v1
#       - name: set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8
#       - name: Unit tests
#         run: bash ./gradlew test --stacktrace

  apkbuild:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make Directories
        run: mkdir app/build/outputs/apk/release/
      - name: Build release APK
        run: bash ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk
