# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    # Compile the app and push to playstore
    - name: Upload Android Release to Play Store (internal track publishing is default)
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountPlainText: "{\"type\": \"service_account\", \"project_id\": \"api-5685426291824431811-410472\",  \"private_key_id\": \"45111924eef588e474f88ed7c2bdd352cfb57530\", \"private_key\": \"-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDB32dRtBKxFgEw\nr8JWnD3U4GbOQEBUFEZ/fwpLvYT+vTYgBmVyaMYQ5hI8uVisvjrwtXWtMgCmmW/x\n1MFs3ee9dzOS97JQaejgIqZR70oGpooTEtTVZ4pEwd+rwzI62gjktSHvHRBVHF71\njtAIR9wIaHGq4VDNl6yPZiT918hrELhmqJEXG8ribEYzZshlaEdrYd8tYXXrIka0\nCnoV1sKos67asDOQmgGcX059B55KNfkUTiLwV9C7VblpmBv1BZORmsLL3+2GnoG4\nrkbEfr8HElm9fcMfbfyPWsXdMyvKL6/3D1WOaeBiWRbuVUIqwR0PX13w0LwF/gy4\nPEAKsZvxAgMBAAECggEAIEAfmdHQwjCc5hJ2y52WE5F4yJqbmOD+kTr65XqTYyTq\nmg02Vv/i4vDC2+MhQysp9tzYxITq4svneV0hCBEp+bSYmbwmp4XWvWJGNJ8Pu2d8\n1ItvaEifEa0GnjYMZwnaLOGM0ZAOJXpguYyWQqphieyF7B0rKegvRnOBd9CrgFOv\nBgrI2Rul45kMUn2mXD99gW7JusKAZWbDfZtdD/9/lx01S83YDB1ILyT6vgYMKjuE\nuu5Is/vAl70aV2MSiBwI+rZUc/gVsdlFM+uk+o4ev1KIKVZEqGS5YNCw4wo/qMV7\npNkVNBAh/mfZsNEdy7CQTPQ0/2miuEgM5x0hSC41+QKBgQD8cwfSm8wdzeieSuO8\nilLCalc2SW3cIvFi/5qalozypllv/AtWY/VwlHvmYnXlKO/jgA/mUD5JpoN+NTWK\nkwfhfIHNZNdgx+lBRxoCTPi9sO1Lg4J/1vF/wM37VZUWJ5Vqt9tre31tP5sgKlkC\nMtvTEGwKDmoT+F52R+JwMTbEawKBgQDEmXY4ixRWWwgwlXr+2WWZRVH4dTSSUShG\nLemWb7rpQui5a+51tseAKSiKRRmVznvh3H8mQ6oFnSoZSQQUGjeHkASkkhYtXOgW\nwj5BaNhNYlNHtp0Nro2ie5At9WRxhP0SnLDWRnVlILnsOuD/F6KBtNRhLyAFCynG\nRIhkCWUYEwKBgAzTw3f+FpcFGWbBo2S3GpFqWdgWTxC6bc17810bfTnvHehExEa1\neYko4krIgfkM5XOH1Eb9mMyhO1k0Vu4dnm7kpqvLDe6K+d0pQbcQNitdTBFkM0NP\npqG5KD43EQY5KKxtfyas9aiRbM5rmG42K1lEIlk4dkdhfVtBN84/kerVAoGBALUA\n3Tk9wyGmeinQ1gagvMuaaNepgRddJQlH6BGbGKj98yoT1t4FxDOYsTxsVhv4mVHf\nIilmjrjQdBwHf3vKj2l+DOg/n69wJDYf7BVopAzLBAW4eWxJUxlPTfUiQrHJUP67\nyIvfHuJWeRanNtNlPTbR997p9j7ugi2Kl1AS3kKFAoGAAaYv1MKLA5WdDoJOoIEU\nE940oERmf9RZ64sqVC46XbIi6WSixYWtdxtF64h7mdACmxAuwE9IVL6g80J7Hkws\n3DkOchE7qFI7EhOr14l7AudyPs4MIi5e3kA9c7HHD7QxR97juRwBv+9QTvSf1Zer\nC2agJdVQcUzH6dK8giGjscc=\n-----END PRIVATE KEY-----\n\",\"client_email\": \"test-service-account@api-5685426291824431811-410472.iam.gserviceaccount.com\",\"client_id\": \"113474262437620211482\",\"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\"token_uri\": \"https://oauth2.googleapis.com/token\",\"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/test-service-account%40api-5685426291824431811-410472.iam.gserviceaccount.com\"}"
        packageName: com.darvis.redisandroid
        releaseFile: app/release/app-release.apk
        track: internal
        userFraction: 0.33
        whatsNewDirectory: distribution/whatsnew
        mappingFile: app/release/mapping/mapping.txt
        
        run: echo Publishing to Google Play Store $track Track

